shellcheck related changes

diff --git a/tools/picon b/tools/picon
--- a/tools/picon
+++ b/tools/picon
@@ -9,7 +9,7 @@ tmp_channels="$tmpdir/tmp.chconf"
 function usage {
 	echo "########## PICON ##########" 1>&2
 	echo "Link logos from the input directory [-i] to the output directory [-o] based on VDR 'channels.conf' [-c]." 1>&2
-	if [ ! -z "${1}" ]; then
+	if [ -n "${1}" ]; then
 		echo "ERROR: $1" 1>&2
 	fi
 	echo "Usage: $0 [-c <channels.conf>] [-i <Input Dir>] [-o <Output Dir>] [-r <remove content of OutputPath>] [-s <silent>]" 1>&2
@@ -21,8 +21,8 @@ function prepare {
 	local input="$1"
 	local output="$2"
 
-	iconv -sc -f UTF-8 -t UTF-8 -o $output $input	# convert to utf8
-	sed -i '/^\./d' "$output"			# remove unnamed channels
+	iconv -sc -f UTF-8 -t UTF-8 -o "$output" "$input"	# convert to utf8
+	sed -i '/^\./d' "$output"							# remove unnamed channels
 }
 
 function servicelist {
@@ -31,37 +31,38 @@ function servicelist {
 
 	if [ -f "$input" ]; then
 		local tempfile="$tmpdir/tmp.servicelist"
-		grep -o '.*:.*:.*:.*:.*:.*:.*:.*:.*:.*:.*:.*:0' $input | sort -u | while read channel; do
-			local IFS=":"
-			local vdrchannel=($channel)
+		grep -o '.*:.*:.*:.*:.*:.*:.*:.*:.*:.*:.*:.*:0' "$input" | sort -u | while read -r channel; do
 			local IFS=";"
+			local channelname channeltype namespace nid sid tid unique_id
+			local -a vdrchannel=()
 
-			local sid=$(printf "%x\n" ${vdrchannel[9]})
-			local tid=$(printf "%x\n" ${vdrchannel[11]})
-			local nid=$(printf "%x\n" ${vdrchannel[10]})
+			mapfile -d ':' -t vdrchannel < <(printf "%s" "$channel")
+
+			sid=$(printf "%x\n" "${vdrchannel[9]}")
+			tid=$(printf "%x\n" "${vdrchannel[11]}")
+			nid=$(printf "%x\n" "${vdrchannel[10]}")
 
 			case ${vdrchannel[3]} in
-				*"W") local namespace=$(printf "%x\n" $(sed -e 's/S//' -e 's/W//' <<< "${vdrchannel[3]}" | awk '{printf "%.0f\n", 3600-($1*10)}'));;
-				*"E") local namespace=$(printf "%x\n" $(sed -e 's/S//' -e 's/E//' <<< "${vdrchannel[3]}" | awk '{printf "%.0f\n", $1*10}'));;
-				"T") local namespace="EEEE";;
-				"C") local namespace="FFFF";;
+				*"W") namespace=$(printf "%x\n" "$(sed -e 's/S//' -e 's/W//' <<< "${vdrchannel[3]}" | awk '{printf "%.0f\n", 3600-($1*10)}')");;
+				*"E") namespace=$(printf "%x\n" "$(sed -e 's/S//' -e 's/E//' <<< "${vdrchannel[3]}" | awk '{printf "%.0f\n", $1*10}')");;
+				"T") namespace="EEEE";;
+				"C") namespace="FFFF";;
 			esac
 			case ${vdrchannel[5]} in
-				"0") local channeltype="2";;
-				*"=2") local channeltype="1";;
-				*"=27") local channeltype="19";;
+				"0") channeltype="2";;
+				*"=2") channeltype="1";;
+				*"=27") channeltype="19";;
 			esac
 
-			local unique_id=$(sed -e 's/.*/\U&\E/' <<< "$sid"'_'"$tid"'_'"$nid"'_'"$namespace")
+			unique_id=$(echo "$sid"'_'"$tid"'_'"$nid"'_'"$namespace" | sed -e 's/.*/\U&\E/')
 			local serviceref='1_0_'"$channeltype"'_'"$unique_id"'0000_0_0_0'
-			local channelname=(${vdrchannel[0]})
-			local channelname=$(echo "${channelname[0]}" | sed -e 's/^[ \t]*//' -e 's/|//g' -e 's/§//g' -e 's/\//_/g' | cut -f1 -d"," | tr '[:upper:]' '[:lower:]')
+			channelname=$(echo "${vdrchannel[0]}" | sed -e 's/^[ \t]*//' -e 's/|//g' -e 's/§//g' -e 's/\//_/g' | cut -f1 -d"," | tr '[:upper:]' '[:lower:]')
 
-			echo -e "$serviceref█$channelname" >> $tempfile
+			echo -e "$serviceref█$channelname" >> "$tempfile"
 		done
 
 		sort -t $'\t' -k 2,2 -o "$output" "$tempfile"
-		rm $tempfile
+		rm "$tempfile"
 	else
 		echo "$input not found"
 	fi
@@ -71,18 +72,20 @@ function linkpicons {
 	local input="$1"
 	local output="$2"
 
-	cd "$output"
+	cd "$output" || exit 1
 
-	find "$output" -xtype l -delete		# delete broken symlinks
+	find "$output" -xtype l -delete						# delete broken symlinks
 
 	for FILE in "$input"/*.png; do
-		local chname=$(basename "$FILE" .png)
+		local chname
+		chname=$(basename "$FILE" .png)
 		local IFS=$'\n'
-		local picon=($(grep -i "█$chname" "$slist" | sed 's/█/\'$'\t/g' | cut -f 1 | sed 's/$/.png/'))
+		local -a picon=()
+		mapfile -t picon < <(grep -i "█$chname" "$slist" | sed 's/█/\'$'\t/g' | cut -f 1 | sed 's/$/.png/')
 
 		for i in "${picon[@]}"; do
-			if [ ! -z "$i" ] && [ ! -L "$i" ]; then
-				if [ -L "$FILE" ]; then		# prevent link chains
+			if [ -n "$i" ] && [ ! -L "$i" ]; then
+				if [ -L "$FILE" ]; then					# prevent link chains
 					FILE="$(readlink -e "$FILE")"
 				fi
 				ln -s "$FILE" "$i"
@@ -123,7 +126,7 @@ else
 	channels_conf=$CHCONF
 fi
 
-if [ -z "$LOGODIR" ] && [ ! -d "$LOGODIR" ]; then usage "Logo directory: Parameter is missing or directory does not exist!"; fi
+if [ -z "$LOGODIR" ] && [ ! -d "$LOGODIR" ]; then usage "Input directory: Parameter is missing or directory does not exist!"; fi
 if [ -z "$OUTDIR" ]; then usage "Output directory: Parameter is missing!"; fi
 if [ ! -d "$OUTDIR" ]; then mkdir -p "$OUTDIR"; fi
 
@@ -137,4 +140,4 @@ linkpicons "$LOGODIR" "$OUTDIR"
 
 
 ### cleanUp
-rm -rf $tmpdir
+rm -rf "$tmpdir"
diff --git a/tools/svg2png b/tools/svg2png
--- a/tools/svg2png
+++ b/tools/svg2png
@@ -12,6 +12,7 @@ WIDTH=800
 OVERWRITE="false"
 FIXED="false"
 SQUARE="false"
+SUBDIRS="false"
 debug="false"
 
 ## Do not change ##
@@ -23,7 +24,7 @@ trap 'echo oh, I am slain; exit 130' INT
 ## Usage Message ##
 function usage {
 	echo "########## svg2png ##########" 1>&2
-	if [ ! -z "${1}" ]; then
+	if [ -n "${1}" ]; then
 		echo "ERROR: $1" 1>&2
 	fi
 	echo "Usage: $0 [-i <input dir>] [-o <output dir>] [-w <width>] [-r <fixed rectangle>] [-s <fixed square>] [-u <unlink>] [-f <overwrite>] [-d <debug>]" 1>&2
@@ -40,7 +41,7 @@ while getopts "di:o:w:h:rsuf" o; do
 			debug="true"
 			;;
 		i)
-			INPUT_DIR=$(readlink -e ${OPTARG})
+			INPUT_DIR=$(readlink -e "${OPTARG}")
 			;;
 		o)	OUTPUT_DIR=${OPTARG}
 			;;
@@ -75,12 +76,12 @@ fi
 
 
 ## width & height ##
-if [ -z ${HEIGHT} ] && [ $FIXED = "true" ] && [ $SQUARE = "true" ]; then
+if [ -z "${HEIGHT}" ] && [ $FIXED = "true" ] && [ $SQUARE = "true" ]; then
 	HEIGHT=$WIDTH
 	if [ $debug = "true" ]; then
 		echo "Square Format (W x H): $WIDTH x $HEIGHT px"
 	fi
-elif [ -z ${HEIGHT} ] && [ $FIXED = "true" ] && [ $SQUARE = "false" ] ; then
+elif [ -z "${HEIGHT}" ] && [ $FIXED = "true" ] && [ $SQUARE = "false" ] ; then
 	HEIGHT=$(awk -v wdth="$WIDTH" 'BEGIN {printf ("%d\n", wdth/(16/9))}')
 	if [ $debug = "true" ]; then
 		echo "Rectangle Format (W x H): $WIDTH x $HEIGHT px"
@@ -105,14 +106,14 @@ OUTPUT_DIR=$(readlink -e "$OUTPUT_DIR")
 ## Variables ##
 FORMAT=$(echo -e "$WIDTH"x"$HEIGHT")
 WORKDIR=$(mktemp -d --suffix=_svg2png)
-SUBDIR=$( ls -1p "$INPUT_DIR" | grep / | sed 's/\///g' )
-cd "$WORKDIR"
+mapfile -t SUBDIR < <(find "$INPUT_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n')
+cd "$WORKDIR" || exit 1
 
 
 
 # Copy and resize .png files
-pngfile=`ls -1 "$INPUT_DIR"/*.png 2>/dev/null | wc -l`
-if [ $pngfile != 0 ]; then
+pngfile=$(find "$INPUT_DIR" -type f -name "*.png" | wc -l)
+if [ "$pngfile" -gt 0 ]; then
 	mogrify -path "$OUTPUT_DIR" -auto-orient -thumbnail "$WIDTH"x "$INPUT_DIR"/*.png
 fi
 
@@ -127,13 +128,13 @@ for file in "$INPUT_DIR"/*.svg; do
 		if [ -L "$file" ] && [ ! -e "$file" ]; then
 			continue
 		elif [ -L "$file" ]; then
-			cd "$OUTPUT_DIR"
+			cd "$OUTPUT_DIR" || exit 1
 			destination="$(basename "$(readlink "$file")" .svg).png"
-			ln -s "$destination" "$pngname"
+			ln -sf "$destination" "$pngname"
 		elif [ $FIXED = "true" ]; then
-			convert -density $WIDTH -background none "$file" -resize "$FORMAT" -gravity center -extent "$FORMAT" "$OUTPUT_DIR/$pngname" || echo "^^ ERROR converting $file ^^"
+			convert -density "$WIDTH" -background none "$file" -resize "$FORMAT" -gravity center -extent "$FORMAT" "$OUTPUT_DIR/$pngname" || echo "^^ ERROR converting $file ^^"
 		else
-			rsvg-convert --keep-aspect-ratio --width=$WIDTH "$file" --output="$OUTPUT_DIR/$pngname"
+			rsvg-convert --keep-aspect-ratio --width="$WIDTH" "$file" --output="$OUTPUT_DIR/$pngname"
 		fi
 		if [ $debug = "true" ]; then
 			echo "DONE: '$pngname'"
@@ -148,54 +149,67 @@ done
 
 
 ## Subdirs ##
-for prefix in ${SUBDIR[@]}; do
-	for filename in "$INPUT_DIR/$prefix"/*; do
-		case $(file --mime-type -b "$filename") in
-			image/png)	# Copy, rename and resize .png files
-				OUTFILE=$(echo -e "$OUTPUT_DIR"/"$prefix"_"$filename")
-				convert "$filename" -resize "$WIDTH" "$OUTFILE"
-				if [ $debug = "true" ]; then
-					echo "Converted $prefix/$filename to $prefix"_"$filename"
-				fi
-			;;
-			image/svg*)	# Rename and Convert .svg to .png
-				pngname="$(basename "$filename" .svg).png"
-				OUTFILE=$(echo -e "$OUTPUT_DIR"/"$prefix"_"$pngname")
-				if [ $FIXED = "true" ] ; then
-					convert -density $WIDTH -background none "$filename" -resize "$FORMAT" -gravity center -extent "$FORMAT" "$OUTFILE" || echo "^^ ERROR converting $filename ^^"
-				else
-					rsvg-convert --keep-aspect-ratio --width=$WIDTH "$filename" --output="$OUTFILE"
-				fi
-				if [ $debug = "true" ]; then
-					echo "Converted $prefix/$filename to $prefix"_"$pngname"
-					exit 0
-				fi
-			;;
-		esac
+if [ "${SUBDIRS:="false"}" = "true" ]; then
+	if [ $debug = "true" ]; then
+		echo "Processing subdirs"
+	fi
+	for prefix in "${SUBDIR[@]}"; do
+		for infile in "$INPUT_DIR/$prefix"/*; do
+			filename="$(basename "$infile")"
+			pngname="$(printf '%s' "$filename" | sed -e 's/\.[^.]*$//').png"
+			case $(file --mime-type -b "$infile") in
+				image/png)		# Copy, rename and resize .png files
+					OUTFILE=$(echo -e "$OUTPUT_DIR"/"$prefix"_"$filename")
+					convert "$infile" -resize "$WIDTH" "$OUTFILE"
+					if [ $debug = "true" ]; then
+						echo "Converted $prefix/$filename to ${prefix}_${filename}"
+					fi
+				;;
+				image/svg*)		# Rename and Convert .svg to .png
+					OUTFILE=$(echo -e "$OUTPUT_DIR"/"$prefix"_"$pngname")
+					if [ $FIXED = "true" ]; then
+						convert -density "$WIDTH" -background none "$infile" -resize "$FORMAT" -gravity center -extent "$FORMAT" "$OUTFILE" || echo "^^ ERROR converting $filename ^^"
+					else
+						rsvg-convert --keep-aspect-ratio --width="$WIDTH" "$infile" --output="$OUTFILE"
+					fi
+					if [ $debug = "true" ]; then
+						echo "Converted $prefix/$filename to ${prefix}_${pngname}"
+					fi
+				;;
+				inode/symlink)	# Modify (copy) symlinks
+					cd "$OUTPUT_DIR" || exit 1
+					destination="$(basename "$(readlink "$infile")" | sed -e 's/\.[^.]*$//').png"
+					ln -sf "$destination" "${prefix}_${pngname}"
+					if [ $debug = "true" ]; then
+						echo "Converted symlink ${prefix}_${pngname} -> $destination"
+					fi
+				;;
+			esac
+		done
 	done
-done
+fi
 
 
 
 ## Unlink ##
 if [ ${UNLINK:="false"} = "true" ]; then
-	UNL_TMP_DIR=$(mktemp -d --tmpdir=$WORKDIR --suffix=_unlink)
+	UNL_TMP_DIR=$(mktemp -d --tmpdir="$WORKDIR" --suffix=_unlink)
 	if [ -d "$UNL_TMP_DIR" ]; then
 		mkdir -p "$UNL_TMP_DIR"
 	fi
 
-	LINKS=($(find "$OUTPUT_DIR" -type l -print))
+	mapfile -t LINKS < <(find "$OUTPUT_DIR" -type l -print)
 
-	for unlink in ${LINKS[@]}; do
-		UN_INPUT=$(readlink -e -f $unlink)
-		UN_OUTPUT=$(basename $unlink)
+	for unlink in "${LINKS[@]}"; do
+		UN_INPUT=$(readlink -e -f "$unlink")
+		UN_OUTPUT=$(basename "$unlink")
 		cp "$UN_INPUT" "$UNL_TMP_DIR/$UN_OUTPUT"
 	done
 
-	mv "$UNL_TMP_DIR"/* "$OUTPUT_DIR" 2>/dev/null | true
+	mv "$UNL_TMP_DIR"/* "$OUTPUT_DIR" 2>/dev/null || true
 fi
 
 
 
 ## CleanUp ##
-rm -rf $WORKDIR
+rm -rf "$WORKDIR"
